// Local orchestration for the dev loop and the source for the published Docker
// Compose topology. Provisions the backing services, then launches the two
// hosts with their connection strings injected as environment variables - no
// credential is ever written to a tracked file.

var builder = DistributedApplication.CreateBuilder(args);

// Publish target for the VPS: `aspire publish` renders this graph into a Docker
// Compose topology. Inert during the local dev loop. Generated credentials are
// emitted as Compose environment variables into an untracked .env file, never
// into the committed compose YAML.
builder.AddDockerComposeEnvironment("jobspect-compose");

// One PostgreSQL server. Every module owns a private schema inside the single
// "jobspect" database; the server password is generated by Aspire and persisted
// to the AppHost user-secrets store. A data volume keeps dev data across runs.
var postgres = builder
    .AddPostgres("postgres")
    .WithDataVolume();

var database = postgres.AddDatabase("jobspect");

// Redis backs the cache, the worker queue (Streams) and rate-limit state. It is
// reconstructable, so it runs without a persistent volume.
var cache = builder.AddRedis("cache");

// The ES256 keypair access tokens are signed and validated with. Declared here
// rather than in the API's own user-secrets so that one declaration covers both
// ways the key has to arrive: locally the values resolve from this project's
// user-secrets store, and publishing renders them as ${...} references in the
// compose file, leaving the real values to the deployment host's .env. Neither
// key is ever written to a tracked file.
//
// Both are marked secret. The public half is not confidential, but marking it so
// keeps it out of the generated compose YAML for the same reason as the private
// half - the deployment supplies the pair together or not at all.
var jwtPrivateKey = builder.AddParameter("identity-jwt-private-key", secret: true);
var jwtPublicKey = builder.AddParameter("identity-jwt-public-key", secret: true);

// Schema first. A one-shot that applies every module's migrations and exits;
// both hosts wait for it to succeed, so neither can start against a database that
// is a migration behind. Nothing migrates on startup - two instances of a host
// racing to alter one schema is the failure this shape exists to prevent.
var migrations = builder.AddProject<Projects.Jobspect_MigrationService>("migrations")
    .WithReference(database)
    .WaitFor(database);

// The API host: serves the modules, depends on both backing services. It is the
// only host that carries the signing keys - it issues the tokens and validates
// them. The worker composes Identity's profile query alone, which reads a
// timezone and touches no token.
builder.AddProject<Projects.Jobspect_Api>("api")
    .WithReference(database)
    .WithReference(cache)
    .WithEnvironment("Identity__Jwt__PrivateKeyPem", jwtPrivateKey)
    .WithEnvironment("Identity__Jwt__PublicKeyPem", jwtPublicKey)
    .WaitForCompletion(migrations)
    .WaitFor(cache);

// The worker host: the Quartz.NET scheduler over the Postgres job store. Redis
// Streams consumers for push delivery arrive with the mobile client.
builder.AddProject<Projects.Jobspect_Worker>("worker")
    .WithReference(database)
    .WithReference(cache)
    .WaitForCompletion(migrations)
    .WaitFor(cache);

builder.Build().Run();
