// Local orchestration for the dev loop and the source for the published Docker
// Compose topology. Provisions the backing services, then launches the two
// hosts with their connection strings injected as environment variables - no
// credential is ever written to a tracked file.

var builder = DistributedApplication.CreateBuilder(args);

// Publish target for the VPS: `aspire publish` renders this graph into a Docker
// Compose topology. Inert during the local dev loop.
//
// The output is not tracked. This file is the source of truth, so a committed
// copy of what it renders would be a snapshot that goes stale the first time a
// resource is added here - and unlike the API contract, nothing generates from
// it and no gate would catch the drift. Generated credentials are emitted as
// Compose environment variables into an untracked .env beside it, which doubles
// as the deployment's checklist: every variable the topology reads, with the
// values left for the host to fill in.
builder.AddDockerComposeEnvironment("jobspect-compose");

// One PostgreSQL server. Every module owns a private schema inside the single
// "jobspect" database; the server password is generated by Aspire and persisted
// to the AppHost user-secrets store. A data volume keeps dev data across runs.
//
// Persistent, and the two go together: the default lifetime builds a fresh
// container per run and removes it only on a graceful shutdown, so every stop
// that isn't Ctrl+C orphans one and the next run makes another. Reusing a single
// named container per AppHost is what the data volume already implies, and it
// also stops each restart waiting for the server to initialise. The price is
// that neither container below is ever removed automatically - which is the
// intent: two forever rather than two per run.
var postgres = builder
    .AddPostgres("postgres")
    .WithDataVolume()
    .WithLifetime(ContainerLifetime.Persistent);

var database = postgres.AddDatabase("jobspect");

// Redis backs the cache, the worker queue (Streams) and rate-limit state. It is
// reconstructable, so it runs without a persistent volume - persistent here is
// about not leaking a container per run, not about keeping what is inside it.
var cache = builder
    .AddRedis("cache")
    .WithLifetime(ContainerLifetime.Persistent);

// The ES256 keypair access tokens are signed and validated with. Declared here
// rather than in the API's own user-secrets so that one declaration covers both
// ways the key has to arrive: locally the values resolve from this project's
// user-secrets store, and publishing renders them as ${...} references in the
// compose file, leaving the real values to the deployment host's .env. Neither
// key is ever written to a tracked file.
//
// Both are marked secret. The public half is not confidential, but marking it so
// keeps it out of the generated compose YAML for the same reason as the private
// half - the deployment supplies the pair together or not at all.
var jwtPrivateKey = builder.AddParameter("identity-jwt-private-key", secret: true);
var jwtPublicKey = builder.AddParameter("identity-jwt-public-key", secret: true);

// The web client's two secrets, declared the same way and for the same reasons.
//
// The session secret signs the opaque id the browser cookie carries; the tokens
// themselves never leave this process. The encryption key is read by Next
// itself rather than by any code here: it encrypts the values a Server Action
// closes over, and Next mints a fresh one per build when it is unset. That is
// invisible with a single instance and breaks the moment there are two, because
// a client that loaded a page from one instance posts its action back to the
// other, which cannot decrypt it. The failure surfaces mid-session as "Failed
// to find Server Action", so the key has to be pinned before a second instance
// exists rather than after.
var webSessionSecret = builder.AddParameter("web-session-secret", secret: true);
var webServerActionsKey = builder.AddParameter("web-server-actions-encryption-key", secret: true);

// Schema first. A one-shot that applies every module's migrations and exits;
// both hosts wait for it to succeed, so neither can start against a database that
// is a migration behind. Nothing migrates on startup - two instances of a host
// racing to alter one schema is the failure this shape exists to prevent.
var migrations = builder.AddProject<Projects.Jobspect_MigrationService>("migrations")
    .WithReference(database)
    .WaitFor(database);

// The API host: serves the modules, depends on both backing services. It is the
// only host that carries the signing keys - it issues the tokens and validates
// them. The worker composes Identity's profile query alone, which reads a
// timezone and touches no token.
//
// The launch profile is named rather than left to be chosen. Its applicationUrl
// is where the API answers - https://localhost:7065 and http://localhost:5001 -
// and a browser client hard-codes one of those in its own configuration. Which
// profile gets picked when none is named is a heuristic, and one that does not
// simply take the first: leaving it implicit means a reordering of that file, or
// a change of heuristic, silently moves the address a client is pointed at.
var api = builder.AddProject<Projects.Jobspect_Api>("api", launchProfileName: "https")
    .WithReference(database)
    .WithReference(cache)
    .WithEnvironment("Identity__Jwt__PrivateKeyPem", jwtPrivateKey)
    .WithEnvironment("Identity__Jwt__PublicKeyPem", jwtPublicKey)
    .WaitForCompletion(migrations)
    .WaitFor(cache);

// The worker host: the Quartz.NET scheduler over the Postgres job store. Redis
// Streams consumers for push delivery arrive with the mobile client.
builder.AddProject<Projects.Jobspect_Worker>("worker")
    .WithReference(database)
    .WithReference(cache)
    .WaitForCompletion(migrations)
    .WaitFor(cache);

// The web client, an orchestrated resource like the two hosts rather than a
// service written into a compose file by hand: `next dev` in the local loop, a
// standalone-output image on publish, and one place that says how it reaches
// the API.
//
// The API address is passed as an explicit endpoint rather than through
// WithReference: the reference renders as https://api:${API_PORT} in the
// published topology, where the API serves plain HTTP and every call would
// fail TLS. Redis arrives by reference, which is already the URL form ioredis
// takes.
// pnpm named explicitly: the default is npm, which cannot read this project's
// lockfile and fails the install outright. --frozen-lockfile makes the install
// reproducible - it refuses to silently re-resolve the dependency graph when
// the lockfile and the manifest disagree, which is the same guarantee the
// backend gets from pinning every package version centrally.
#pragma warning disable ASPIREJAVASCRIPT001 // AddNextJsApp is still experimental.
builder.AddNextJsApp("web", "../src/Jobspect.Web")
    .WithPnpm(installArgs: ["--frozen-lockfile"])
    .WithHttpEndpoint(port: 3000, env: "PORT")
    .WithExternalHttpEndpoints()
    .WithEnvironment("JOBSPECT_API_BASE_URL", api.GetEndpoint("http"))
    .WithEnvironment("SESSION_SECRET", webSessionSecret)
    .WithEnvironment("NEXT_SERVER_ACTIONS_ENCRYPTION_KEY", webServerActionsKey)
    .WithReference(cache)
    .WithHttpHealthCheck("/health/ready")
    .WaitFor(api);
#pragma warning restore ASPIREJAVASCRIPT001

builder.Build().Run();
