// <auto-generated />
using System;
using JobTrail.Modules.Analytics.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobTrail.Modules.Analytics.Persistence.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260730141642_InitialAnalytics")]
    partial class InitialAnalytics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobTrail.Modules.Analytics.Domain.ApplicationFacts", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateOnly?>("AppliedDate")
                        .HasColumnType("date")
                        .HasColumnName("applied_date");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("CampaignRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("campaign_recorded_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("FirstInterviewScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_interview_scheduled_at");

                    b.Property<DateTimeOffset?>("FirstResponseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_response_at");

                    b.Property<string>("Outcome")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("ReachedInterviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reached_interview_at");

                    b.Property<DateTimeOffset?>("ReachedOfferAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reached_offer_at");

                    b.Property<DateTimeOffset?>("ReachedScreeningAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reached_screening_at");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("Stage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset?>("StageEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stage_entered_at");

                    b.Property<DateTimeOffset?>("StageRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stage_recorded_at");

                    b.Property<string>("WorkMode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("work_mode");

                    b.HasKey("ApplicationId")
                        .HasName("pk_application_facts");

                    b.HasIndex("OwnerId", "CampaignId")
                        .HasDatabaseName("ix_application_facts_owner_id_campaign_id");

                    b.ToTable("application_facts", "analytics");
                });
#pragma warning restore 612, 618
        }
    }
}
