// <auto-generated />
using System;
using JobTrail.Modules.Notifications.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobTrail.Modules.Notifications.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20260731152133_InitialNotifications")]
    partial class InitialNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobTrail.Modules.Notifications.Domain.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid?>("InterviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("kind");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<DateTimeOffset>("SourceRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_recorded_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("SubjectAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subject_at");

                    b.Property<DateOnly?>("SubjectDate")
                        .HasColumnType("date")
                        .HasColumnName("subject_date");

                    b.HasKey("Id")
                        .HasName("pk_reminders");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_reminders_application_id");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("ix_reminders_due_at")
                        .HasFilter("state = 'Pending'");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_reminders_rule_id");

                    b.HasIndex("ApplicationId", "InterviewId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_reminders_application_id_interview_id_kind")
                        .HasFilter("state = 'Pending'");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ApplicationId", "InterviewId", "Kind"), false);

                    b.HasIndex("OwnerId", "DueAt", "Id")
                        .HasDatabaseName("ix_reminders_owner_id_due_at_id");

                    b.ToTable("reminders", "notifications");
                });

            modelBuilder.Entity("JobTrail.Modules.Notifications.Domain.ReminderDelivery", b =>
                {
                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uuid")
                        .HasColumnName("reminder_id");

                    b.Property<string>("Channel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.HasKey("ReminderId", "Channel")
                        .HasName("pk_reminder_deliveries");

                    b.ToTable("reminder_deliveries", "notifications");
                });

            modelBuilder.Entity("JobTrail.Modules.Notifications.Domain.ReminderRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DaysAfterApplied")
                        .HasColumnType("integer")
                        .HasColumnName("days_after_applied");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reminder_rules");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasDatabaseName("ix_reminder_rules_owner_id");

                    b.ToTable("reminder_rules", "notifications");
                });

            modelBuilder.Entity("JobTrail.Modules.Notifications.Domain.TrackedApplication", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateOnly?>("AppliedDate")
                        .HasColumnType("date")
                        .HasColumnName("applied_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Stage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset?>("StageRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stage_recorded_at");

                    b.HasKey("ApplicationId")
                        .HasName("pk_tracked_applications");

                    b.HasIndex("OwnerId", "AppliedDate")
                        .HasDatabaseName("ix_tracked_applications_owner_id_applied_date");

                    b.ToTable("tracked_applications", "notifications");
                });

            modelBuilder.Entity("JobTrail.Modules.Notifications.Domain.Reminder", b =>
                {
                    b.HasOne("JobTrail.Modules.Notifications.Domain.ReminderRule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reminders_reminder_rules_rule_id");
                });

            modelBuilder.Entity("JobTrail.Modules.Notifications.Domain.ReminderDelivery", b =>
                {
                    b.HasOne("JobTrail.Modules.Notifications.Domain.Reminder", null)
                        .WithMany()
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reminder_deliveries_reminders_reminder_id");
                });
#pragma warning restore 612, 618
        }
    }
}
