// Local orchestration for the dev loop and the source for the published Docker
// Compose topology. Provisions the backing services, then launches the two
// hosts with their connection strings injected as environment variables - no
// credential is ever written to a tracked file.

var builder = DistributedApplication.CreateBuilder(args);

// Publish target for the VPS: `aspire publish` renders this graph into a Docker
// Compose topology. Inert during the local dev loop. Generated credentials are
// emitted as Compose environment variables into an untracked .env file, never
// into the committed compose YAML.
builder.AddDockerComposeEnvironment("jobtrail-compose");

// One PostgreSQL server. Every module owns a private schema inside the single
// "jobtrail" database; the server password is generated by Aspire and persisted
// to the AppHost user-secrets store. A data volume keeps dev data across runs.
var postgres = builder
    .AddPostgres("postgres")
    .WithDataVolume();

var database = postgres.AddDatabase("jobtrail");

// Redis backs the cache, the worker queue (Streams) and rate-limit state. It is
// reconstructable, so it runs without a persistent volume.
var cache = builder.AddRedis("cache");

// Schema first. A one-shot that applies every module's migrations and exits;
// both hosts wait for it to succeed, so neither can start against a database that
// is a migration behind. Nothing migrates on startup - two instances of a host
// racing to alter one schema is the failure this shape exists to prevent.
var migrations = builder.AddProject<Projects.JobTrail_MigrationService>("migrations")
    .WithReference(database)
    .WaitFor(database);

// The API host: serves the modules, depends on both backing services.
builder.AddProject<Projects.JobTrail_Api>("api")
    .WithReference(database)
    .WithReference(cache)
    .WaitForCompletion(migrations)
    .WaitFor(cache);

// The worker host: the Quartz.NET scheduler over the Postgres job store. Redis
// Streams consumers for push delivery arrive with the mobile client.
builder.AddProject<Projects.JobTrail_Worker>("worker")
    .WithReference(database)
    .WithReference(cache)
    .WaitForCompletion(migrations)
    .WaitFor(cache);

builder.Build().Run();
